name: Say Hello World
on:
  issues:

jobs:
  sayHelloWorld:
    runs-on: ubuntu-latest
    steps:
      - uses: SaemJeon/apps@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}